name: Daniel Crenna
favicon: null
layout_spectrum: 0.01944875973276794
typography_spectrum: 0.708356820512563
title: I Ask.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-673514-15
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.43875247007235885
  lightness: 0.879386360058561
  saturation: 0.32899292651563883
  rhythmicContrast: 0.7421868497040123
purpose: []
